# Prompt Variables
- name : Prompting Variables
  hosts : localhost
  vars_prompt:
    - name : USERNAME
      prompt : "PLEASE ENTER USERNAME"
      private : false

    - name : PASSWORD
      prompt : "PLEASE ENTER PASSWORD"
      private : true
  tasks :
   - name : Printing Variables
     ansible.builtin.debug :
        msg: "Hi {{USERNAME}} YOUR PASSWORD IS {{PASSWORD}}"


