# Conditions
- name : Conditions 
  hosts : localhost
  become : yes
  tasks :
    - name : User Creation
      ansible.builtin.command : id expense
      register : USERINFO
      ignore_errors : true

    - name : Create User
      ansible.builtin.command: adduser expense
      when : USERINFO.rc != 0

    - name : print Hello
      ansible.builtin.debug :
        msg : "HELLO"
    

