# Conditions
- name : Conditions 
  hosts : localhost
  tasks :
    - name : User Creation
      ansible.builtin.command : id expense
      register : USERINFO
    - name : print Hello
      ansible.builtin.debug :
        msg : "HELLO"
    

