# Testing Variables.
- name : "Testing Variable scope"
  hosts: localhost
  vars_files :
    - file1
  vars : 
    #test : "Testing In Play Level"
  tasks :
    - name : Printing Variable
      vars : 
         #test : "Testing In Task Level"
      ansible.builtin.debug :
        msg : "Hello,{{test}}"

