# Variables Practice
- name : Testing Variables
  hosts : localhost
  vars : 
    course : "Devops"
  tasks :
   - name : Task Level Variable
     vars :
       course : "Java"
     ansible.builtin.debug :
       msg: "Course Is {{course}}"
   - name : Play Level Variable
     ansible.builtin.debug :
       msg : "Course Is {{course}}"    
       