# Print Data types
- name : Printing Data Types
  hosts : localhost
  tasks :
   - name : Print
     vars :
      course : 
         name : Java
         price : 30
     ansible.builtin.debug :
      msg : "{{course}}"    

